// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnpdznfxayaevbdarotr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFucGR6bmZ4YXlhZXZiZGFyb3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODUzODQsImV4cCI6MjA2MzQ2MTM4NH0.MlFadBs45ytIbysW6kncr6Sam2KLc9NGF2CU2HRgDwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);